/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

// package uk.lgl.modmenu;

// public final class R {
//     public static final class attr {
//     }
//     public static final class color {
//         public static final int backgroundColor=0x7f050003;
//         public static final int colorAccent=0x7f050002;
//         public static final int colorPrimary=0x7f050000;
//         public static final int colorPrimaryDark=0x7f050001;
//     }
//     public static final class drawable {
//         public static final int ic_launcher_background=0x7f020000;
//         public static final int ic_launcher_foreground=0x7f020001;
//         public static final int ic_launcher_foreground_1=0x7f020002;
//     }
//     public static final class layout {
//         public static final int activity_main=0x7f040000;
//     }
//     public static final class mipmap {
//         public static final int ic_launcher=0x7f030000;
//         public static final int ic_launcher_round=0x7f030001;
//     }
//     public static final class string {
//         public static final int app_name=0x7f060000;
//     }
//     public static final class style {
//         /**  Base application theme. 
//          */
//         public static final int AppTheme=0x7f070000;
//     }
// }

// Conversión directa del archivo R.java a JavaScript
const R = {
    attr: {},
    
    color: {
        backgroundColor: 0x7f050003,
        colorAccent: 0x7f050002,
        colorPrimary: 0x7f050000,
        colorPrimaryDark: 0x7f050001
    },
    
    drawable: {
        ic_launcher_background: 0x7f020000,
        ic_launcher_foreground: 0x7f020001,
        ic_launcher_foreground_1: 0x7f020002
    },
    
    layout: {
        activity_main: 0x7f040000
    },
    
    mipmap: {
        ic_launcher: 0x7f030000,
        ic_launcher_round: 0x7f030001
    },
    
    string: {
        app_name: 0x7f060000
    },
    
    style: {
        // Base application theme.
        AppTheme: 0x7f070000
    }
};

// Funciones auxiliares para trabajar con los recursos
R.getDrawable = function(id) {
    // Devuelve una URL para el drawable basado en su ID
    switch(id) {
        case this.drawable.ic_launcher_background:
        case this.drawable.ic_launcher_foreground:
        case this.drawable.ic_launcher_foreground_1:
        case this.mipmap.ic_launcher:
        case this.mipmap.ic_launcher_round:
            return "https://www.zsensi.xyz/images/logo.png";
        default:
            return "";
    }
};

R.getString = function(id) {
    // Devuelve una cadena basada en su ID
    switch(id) {
        case this.string.app_name:
            return "ZSensi";
        default:
            return "";
    }
};

R.getColor = function(id) {
    // Devuelve un color CSS basado en su ID
    switch(id) {
        case this.color.backgroundColor:
            return "#121212";
        case this.color.colorAccent:
            return "#1a73e8";
        case this.color.colorPrimary:
            return "#3a3a3a";
        case this.color.colorPrimaryDark:
            return "#1f1f1f";
        default:
            return "";
    }
};

// Exponer globalmente
window.R = R;

console.log("[Resources] R class initialized for uk.lgl.modmenu");